completed array-reduce
m-Cho1/rc0522-code-solutions pull request #109
Opened 2022-07-11 23:31 UTC by m-Cho1

![image](https://user-images.githubusercontent.com/96744088/178375659-0e2a9e48-93b8-4eec-813d-929027ce77e9.png)

2022-07-11 23:45 UTC, scbowler requested changes
Looking good, but an update to `sumAllAmounts` is needed. Let me know if you have any questions.

2022-07-11 23:45 UTC, scbowler commented on array-reduce/main.js
> +    initialValue -= current.amount;
While this works it is kind of an oops it worked. Here you should be adding or subtracting from `previous`. then returning `previous`

2022-07-11 23:56 UTC, m-Cho1 commented
Edited sumAllAmounts

2022-07-11 23:57 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-07-11 23:59 UTC, merged

2022-07-12 00:46 UTC, m-Cho1 commented
`// composite:
const combineProp = (previous, current) => {
  const result = Object.assign(previous, current);
  return result;
};
const composite = traits.reduce(combineProp, {});
console.log('composite: ', composite);
`

always add empty object literal if you are looking for to return new object