Javascript carousel
m-Cho1/rc0522-code-solutions pull request #70
Opened 2022-06-08 23:17 UTC by m-Cho1

![javascript-carousel-min](https://user-images.githubusercontent.com/96744088/172733061-265a39f5-781a-4a36-a9ca-44836582daa2.gif)

2022-06-08 23:30 UTC, TimelikeClosure requested changes

2022-06-08 23:30 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +setInterval(carousel, 3000);
The timer should start over each time the user interacts with the carousel.

2022-06-08 23:52 UTC, m-Cho1 commented
Added clearInterval method to functions

2022-06-09 00:01 UTC, TimelikeClosure approved these changes

2022-06-09 00:04 UTC, merged